[package]
name = "delta-rs-bridge"
version = "0.1.0"
edition = "2021"

[lib]
name = "delta_rs_bridge"
crate-type = ["cdylib", "rlib"]

[dependencies]
arrow = { version = "49", features = ["ffi"]}
chrono = "0.4.31"
# deltalake = "0.16.5"
deltalake = { git = "https://github.com/delta-io/delta-rs.git", branch = "main", features = ["azure", "gcs", "s3", "datafusion"] }
flatbuffers = "23.5.26"
libc = "0.2"
serde_json = "1.0.111"
tokio = { version = "1" }
tokio-util = "0.7"

[build-dependencies]
cbindgen = "0.24"
