name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build-lint-test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            checkTarget: true
          - os: ubuntu-latest
            docsTarget: true
            cloudTestTarget: true
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/DeltaLake/Bridge

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Build
        # We intentionally just build debug mode in this CI. We build before
        # regen to confirm no interop header changes.
        run: dotnet build

      - name: Regen confirm unchanged
        if: ${{ matrix.checkTarget }}
        # Needs to be 16.0.0 until https://github.com/dotnet/ClangSharp/pull/506 released
        run: |
          dotnet tool install --global --version 16.0.0 ClangSharpPInvokeGenerator
          ClangSharpPInvokeGenerator @src/Temporalio/Bridge/GenerateInterop.rsp
          npx doctoc README.md
          git config --global core.safecrlf false
          git diff --exit-code

      - name: Check format
        if: ${{ matrix.checkTarget }}
        run: dotnet format --verify-no-changes

      - name: Test
        run: dotnet test --logger "console;verbosity=detailed" --blame-crash -v n

      - name: Upload test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-fail-${{ matrix.os }}
          path: tests/DeltaLake.Tests/TestResults

      - name: Build docs
        if: ${{ matrix.docsTarget }}
        run: |
          dotnet tool update -g docfx
          docfx src/DeltaLake.ApiDoc/docfx.json --warningsAsErrors
